# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3906ac7b78a2001e2b9b50d0346fc91ef606d54bc1292e393adabb5dc4c8cf77cccd8e76fa44592da9dab4b5d50e1c620e0fb649c75b0235a109b6d37b92ca28

test:
  secret_key_base: da5b05fc8134c7ae84f3da549cb71c5bc4320554920e36d43cfaadfe6414f2c09d207044f2483c6652e33383b2a68555c7a136138d3255837439035f7fca3187

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
